language: python
python:
  - "2.7"
  # Disabled due to test failures like:
  # TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'
  # Needs explicit conversion to bytes after string formatting.
  # Example, see https://travis-ci.org/abhinavsingh/proxy.py/jobs/490855017
  #- "3.3"
  #- "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
os:
  - linux
  # No support for OSX Python runtime
  #- osx
  # Windows Python support is currently in early access
  #- windows
script:
  - make
